### ISSUE TITLE
Missing '1.0.2' tag for quay.io/integreatly/application-monitoring-operator image

### ISSUE THREAD

**Issue by paoloyx** [integr8ly/application-monitoring-operator#108]
Hi all,

current master branch won't deploy on Openshift (v3.11 in our case) due to missing `1.0.2` tag for [quay.io/repository/integreatly/application-monitoring-operator](https://quay.io/repository/integreatly/application-monitoring-operator?tab=tags) docker image

It's not possibile to download image, so the `application-monitoring-pod` goes into `ErrImagePullBackoff`

**Comment by paoloyx** [comment]
@davidkirwan is it possibile for you to build/push the tag? Am i supposed to do it by miself? Thanks!

**Comment by davidkirwan** [comment]
@paoloyx ahh yes apologies, missed this last Friday. I'll create it now!

**Comment by davidkirwan** [comment]
@paoloyx done.

**Comment by paoloyx** [comment]
@davidkirwan Yes i've seen, thank you!
