### ISSUE TITLE
How to do offline installation

### ISSUE THREAD

**Issue by sousaaguilherme** [integr8ly/application-monitoring-operator#119]
Hi!

We're running supported Openshift 3.11 in a disconnected installation.
What parameters should we change to deploy this in our environment? Do we have to rebuild the application-monitoring-operator (+ the grafana and prometheus operator?!) ?

Best regards

**Comment by david-martin** [comment]
@sousaaguilherme 
A disconnected installation is not something I'm familiar with.
After some brief reading of https://docs.openshift.com/container-platform/3.11/install/disconnected_install.html#disconnected-syncing-images, 
it looks like the biggest problem is getting the images that are used into the cluster.

If all the requisite images are available on all nodes in the cluster, then in theory the containers for all components should start no matter which node they are scheduled to.
I'm unsure what that process would be (whether to push all the images into the local registry on every node, or to push to a central registry)

@pb82 Is this something you have any thoughts on?

**Comment by sousaaguilherme** [comment]
Thanks for the feedback @david-martin  :)

I'm ok with pulling and pushing all the images to my private registry. Actually, I've been trying to do so with this operator. The problem I think I'm having is that I have to edit manually all the Deployments/Replicasets/etc, to point to the correct images.

Furthermore, I believe som of the images are hardcoded because I don't seem to find references to all of them neither in the Deployments/RS/etc.

Best regards

**Comment by pb82** [comment]
@sousaaguilherme Here is a list of all the images that you need to pull into your on-cluster registry: https://github.com/integr8ly/application-monitoring-operator/blob/master/pkg/controller/applicationmonitoring/templateHelper.go#L139

**Comment by sousaaguilherme** [comment]
Thanks for the feedback @pb82 . Will close the issue since the disconnected installation seems to be out of scope.
Best regards
