### ISSUE TITLE
Failed to provision volume with StorageClass "glusterfs-cns"

### ISSUE THREAD

**Issue by sousaaguilherme** [integr8ly/application-monitoring-operator#121]
I'm having this error while deploying the application-monitoring-operator:

` Failed to provision volume with StorageClass "glusterfs-cns": failed to create volume: failed to create endpoint/service application-monitoring/glusterfs-dynamic-a19ef757-5883-11ea-a191-005056bcda32: failed to create endpoint: Endpoints "glusterfs-dynamic-a19ef757-5883-11ea-a191-005056bcda32" is invalid: metadata.labels: Invalid value: "prometheus-application-monitoring-db-prometheus-application-monitoring-0": must be no more than 63 characters `

I've tracked this problem to the prometheus-operator: https://github.com/helm/charts/issues/13170

As a workaround, they suggest editing the storagespec through the helms "values.yml" like so:

```
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
```

How can this be achieved in the application-monitoring-operator? Right now it's not possible to deploy it with glusterfs.

Best regards

**Comment by david-martin** [comment]
@sousaaguilherme If I'm understanding the problem correct, you may be able change the volumeClaimTemplate, as you suggest, in the Prometheus CR template here https://github.com/integr8ly/application-monitoring-operator/blob/98027589a049d2c4fac264468c221982ef303c78/templates/prometheus.yaml#L90-L97
Does that sound right?

**Comment by sousaaguilherme** [comment]
It worker! :) thanks @david-martin
