### ISSUE TITLE
[BLOCKER] Error pulling prometheus-blackbox-exporter image

### ISSUE THREAD

**Issue by alexkieling** [integr8ly/application-monitoring-operator#58]
prometheus-application-monitoring-0 pod fails to run due to the following error:
`Failed to pull image "registry.connect.redhat.com/bitnami/prometheus-blackbox-exporter:0.14.0-rhel-7-r33-2": rpc error: code = Unknown desc = Get https://registry.connect.redhat.com/v2/bitnami/prometheus-blackbox-exporter/manifests/0.14.0-rhel-7-r33-2: unauthorized: Invalid username or password`

**Comment by david-martin** [comment]
Closing as #65 is merged
