### ISSUE TITLE
Possible error in "Set up pull secrets" documentation

### ISSUE THREAD

**Issue by alexkieling** [integr8ly/application-monitoring-operator#59]
It seems section **Set up pull secrets** should also include the following command:
```
oc secrets link grafana-serviceaccount docker-pull-secret --for=pull
```
Without it, `grafana-deployment` Deployment fails.

**Comment by david-martin** [comment]
This shouldn't be an issue anymore since #65 has merged.
However, keeping this open as the docs need to be updated to remove references to secrets
